### ISSUE TITLE
Comentarios de su documentación

### ISSUE THREAD

**Issue by monzter50** [CodingHall/Overcome#1]
Hola @codinghall, el planteamiento de su objetivo general y específico está bien pero no es necesario escribir preámbulos al momento de redactar los objetivos general; se recomienda expresar directamente el objetivo, comparto un ejemplo en el que se pueden basar.

Ejemplo

* Objetivo general: Analizar la forma en que están preparándose las empresas nacionales para afrontar los retos de la competitividad y los demás cambios que caracterizan el nuevo ambiente de los negocios. 

En los objetivos específicos se debe desprender del general y deben ser formulados de forma que estén orientados al logro del objetivo general .

Ejemplo

* Elaborar un marco teórico sobre la actitud de los directivos de empresas respecto de la innovación y creatividad en las organizaciones productivas.

**Comment by zavalabj** [comment]
Realizamos las modificaciones correspondientes. Se puede cerrar el issue?

**Comment by monzter50** [comment]
Solo en el punto de crear guías sobre temas, juntar todo en una oración que explique la elaboración de sus temas.

**Comment by zavalabj** [comment]
Se hicieron las modificaciones correspondientes a la documentación.

**Comment by zavalabj** [comment]
Aún no considera solucionado el issue?
