### ISSUE TITLE
Elaboración de portafolio (Individual)

### ISSUE THREAD

**Issue by monzter50** [CodingHall/Overcome#11]
Elaborar portafolio aplicando los diferente tipos de prototipo baja, media y alta fidelidad(Vista mobile y desktop)  usando herramientas como adobe XD, ilustrator o  cualquier editor de gráficos vectoriales, separando por temas correspondientes y adjuntar el archivo editable y el pdf.

## Fecha limite 9 de mayo del 2020 a las 11:59 pm

**Comment by Iurisaki-Isaac** [comment]
Tarea subida en la rama develop.

**Comment by zavalabj** [comment]
Agregado a develop. Carpeta con mi nombre

**Comment by LordBeltran** [comment]
Mi tarea está en la carpeta master (Lo subí en tiempo, solo es para que sepa donde está)
