### ISSUE TITLE
Proyecto final 🏆💪

### ISSUE THREAD

**Issue by monzter50** [CodingHall/Overcome#13]
Hola buenos días, adjunto los puntos que se evaluara en este tercer parcial. Cada equipo tendrá 20 minutos para hacer su presentación de su proyecto.
La elaboración de documentación y proyecto tiene una **fecha limite del 20 de mayo del 2020 a las 11:59pm** .
Adjuntar el file del proyecto editable y montar el proyecto cualquier servidor de prueba, se observara también los commit de cada funcionalidad terminada.
# Presentación
- Introducción
- Objetivó general
- Objetivo específicos
- Modelo de negocios
- Solución del problema
- Demostración del producto
## Elaboración de documentación
* Prototipo de alta fidelidad completo
** Uso de patrones de diseño UI
** Flujo del prototipo
## Proyecto
* Funcionalidad.
* El alcance del producto.

**Comment by LordBeltran** [comment]
Profe, está bien esa fecha? por que el calendario marca como fecha final de semestre el día 23 de mayo

**Comment by monzter50** [comment]
Si tienes razón corrígo el issue muchas gracias por la observación.
